name: Build And Deploy 🙏

on: workflow_dispatch

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  checkLicense:
    name: Check for the Unity license 📧
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      - name: Success! - Found a license
        if: ${{ startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 0
      - name: Fail - No License XX
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1

  buildWebGL:
    needs: checkLicense
    name: Build for WebGL 🖥️
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-WebGL
          restore-keys: |
            Library-build-
            Library-

      - uses: webbertakken/unity-builder@v2
        with:
          targetPlatform: WebGL

      - uses: actions/cache@v2
        id: build-cache
        with:
          path: build/WebGL
          key: build-cache-${{ hashFiles('**/webgl.template.js') }}

      - uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL

  name: Install Butler
    uses: itchio/setup-butler@v1.2.2

  deployPages:
    needs: buildWebGL
    name: Deploy to Itch.io 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        id: build-cache
        with:
          path: build/WebGL
          key: build-cache-${{ hashFiles('**/webgl.template.js') }}

      - name: Display structure of root files
        run: ls -R
        working-directory: build/WebGL

      - name: Install Butler
        uses: itchio/setup-butler@v1.2.2

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: itch-io
          folder: build/WebGL

      - name: Publish WebGL build to itch.io 🚀
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCHIO_API_KEY }}
          CHANNEL: HTML
          ITCH_GAME: week2
          ITCH_USER: mittomrum
          BRANCH: itch-io
          PACKAGE: build/WebGL
        if: steps.build-cache.outputs.cache-hit == 'true'
