name: Deploy ✨

on: push
env:
  ITCH_USERNAME: ${{ secrets.ITCH_USERNAME }}
  ITCH_GAME_ID: ${{ secrets.ITCH_GAME_ID }}
jobs:
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    name: Deploy - Itch.io ${{ matrix.template }}
    steps:
      - uses: actions/cache@v2
        id: build-cache
        with:
          path: build/WebGL
          key: build-cache-${{ hashFiles('**/webgl.template.js') }}

      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.ITCH_IO_API_KEY}}
          gameData: ./build/${{ matrix.template }}
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
